trigger: none

variables:
  projectName: 'SRE_AZURE_CLASS'
  buildPipelineName: 'frontend_deploy'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Installing Azure DevOps CLI extension..."
    az extension add --name azure-devops || echo "Already installed."

    echo "Logging into Azure DevOps CLI using PAT..."
    echo "$(MY_DEVOPS_PAT)" | az devops login

    echo "Setting DevOps defaults..."
    az devops configure --defaults organization=https://dev.azure.com/opscosolutions project=$(projectName)

    echo "Resolving Pipeline ID for: $(buildPipelineName)..."
    PIPELINE_ID=$(az pipelines show --name "$(buildPipelineName)" --query id --output tsv)

    if [ -z "$PIPELINE_ID" ]; then
      echo "##vso[task.complete result=Failed;]Pipeline '$(buildPipelineName)' not found!"
      exit 1
    fi

    echo "Pipeline ID: $PIPELINE_ID"

    echo "Listing last 5 successful builds..."
    az pipelines build list \
      --definition-ids $PIPELINE_ID \
      --status completed \
      --result succeeded \
      --top 5 \
      --query '[].{BuildID:id, BuildNumber:buildNumber, Result:result, FinishTime:finishTime}' \
      --output table
  displayName: 'List Last 5 Successful Builds Using PAT'
  env:
    my_devops_pat: $(MY_DEVOPS_PAT)
