trigger: none

variables:
  projectName: 'SRE_AZURE_CLASS'
  buildPipelineName: 'frontend_deploy'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Installing Azure DevOps CLI extension (if needed)..."
    az extension add --name azure-devops || echo "Already installed."

    echo "Setting Azure DevOps defaults..."
    az devops configure --defaults organization=https://dev.azure.com/opscosolutions project=$(projectName)

    echo "Getting Pipeline ID for $(buildPipelineName)..."
    PIPELINE_ID=$(az pipelines show --name "$(buildPipelineName)" --query id --output tsv)
    echo "Pipeline ID: $PIPELINE_ID"

    echo "Listing recent builds for pipeline ID: $PIPELINE_ID..."
    az pipelines build list \
      --definition-ids $PIPELINE_ID \
      --status completed \
      --result succeeded \
      --top 5 \
      --query '[].{BuildID:id, BuildNumber:buildNumber, Result:result, FinishTime:finishTime}' \
      --output table
  env:
    AZURE_DEVOPS_EXT_PATVAR: $(System.AccessToken)
  displayName: 'List Last 5 Successful Builds for Pipeline'