trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'AzureDevopsConnection'
  projectName: 'SRE_AZURE_CLASS'

steps:
- task: AzureCLI@2
  displayName: 'Test Azure DevOps CLI - List Pipelines'
  inputs:
    azureSubscription: '$(azureSubscription)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Installing Azure DevOps CLI extension (if needed)..."
      az extension add --name azure-devops || echo "Azure DevOps CLI extension already installed."

      echo "Setting default organization and project for CLI..."
      az devops configure --defaults organization=https://dev.azure.com/SRE_AZURE_CLASS project=$(projectName)

      echo "Listing all pipelines in project: $(projectName)..."
      az pipelines list --query '[].name' --output table
